name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to get all files
      - name: Checkout
        uses: actions/checkout@v4
        
      # Generate the env.json file (or any other necessary files) if needed
      - name: Generate env.json
        run: |
          echo '{"key": "value"}' > ./env.json  # Example: Create env.json file

      # Optional: Validate that required files exist
      - name: Check for required files
        run: |
          if [[ ! -f ./env.json ]]; then
            echo "Error: env.json is missing!"
            exit 1
          fi
          
      # Setup Pages for GitHub Pages deployment
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Archive the repository (including the generated files)
      - name: Archive files for GitHub Pages
        run: |
          tar -czf artifact.tar.gz ./index.html ./README.md ./env.json  # Archive the specific files you want
          
      # Upload the artifact (ensure the correct path is provided)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: artifact.tar.gz  # Upload the artifact containing all necessary files

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
